on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Github action'
        run: pwd
        

      - uses: actions/checkout@v3  

      - name: 'printing folder contents'
        run: ls

      - name: 'Testing Printing'
        run: echo 'Mohamed Ali'




